use testbus1;
INSERT INTO Driver VALUES(1,'Dinesh',45,10000)
INSERT INTO Driver VALUES(2,'Ramesh',25,10000)
INSERT INTO Driver VALUES(3,'Suresh',35,10000)
INSERT INTO Driver VALUES(4,'Prakash',25,10000)
INSERT INTO Driver VALUES(5,'Seenapa',50,10000)
INSERT INTO Driver VALUES(6,'Manjunath',33,10000)
INSERT INTO Driver VALUES(7,'Manu',44,10000)
INSERT INTO Driver VALUES(8,'Oblesh',35,10000)
INSERT INTO Driver VALUES(9,'Surya',44,10000)
INSERT INTO Driver VALUES(10,'Dhanush',35,10000)
INSERT INTO Driver VALUES(11,'Basya',41,10000)
INSERT INTO Driver VALUES(12,'AnnTamma',55,10000)
INSERT INTO Driver VALUES(13,'Shivraj',45,10000)

INSERT INTO Buses VALUES(1,'TATA Star 60',60,55,1)
INSERT INTO Buses VALUES(2,'AL SB 70',70,60,2)
INSERT INTO Buses VALUES(3,'AL SB 70',70,59,3)
INSERT INTO Buses VALUES(4,'AL SB 70',70,69,4)
INSERT INTO Buses VALUES(5,'TATA Star 70',70,60,7)
INSERT INTO Buses VALUES(6,'Mazda School',50,50,5)
INSERT INTO Buses VALUES(7,'Force Traveller',20,19,6)
INSERT INTO Buses VALUES(8,'Marcopolo School',70,60,8)
INSERT INTO Buses VALUES(9,'Marcopolo School',70,58,10)
INSERT INTO Buses VALUES(10,'Marcopolo School',70,62,9)
INSERT INTO Buses VALUES(11,'TATA Mini School',40,25,11)
INSERT INTO Buses VALUES(12,'AL SB 50',50,44,13)
INSERT INTO Buses VALUES(13,'TATA Mini School',40,29,12)

INSERT INTO Buses (Bus_ID, Model, Capacity, Occupancy)
VALUES (14, 'Force Traveller',20,0);
INSERT INTO Buses (Bus_ID, Model, Capacity, Occupancy)
VALUES (15, 'TATA STAR 60',60,0);

INSERT INTO Route VALUES(1,'6:00:00','7:20:00',1)
INSERT INTO Route VALUES(2,'6:10:00','7:45:00',2)
INSERT INTO Route VALUES(3,'6:05:00','7:35:00',3)
INSERT INTO Route VALUES(4,'6:15:00','7:45:00',4)
INSERT INTO Route VALUES(5,'6:10:00','7:20:00',5)
INSERT INTO Route VALUES(6,'6:20:00','7:10:00',6)
INSERT INTO Route VALUES(7,'6:05:00','7:25:00',7)
INSERT INTO Route VALUES(8,'6:10:00','7:45:00',8)
INSERT INTO Route VALUES(9,'6:15:00','7:35:00',9)
INSERT INTO Route VALUES(10,'6:20:00','7:40:00',10)
INSERT INTO Route VALUES(11,'6:10:00','7:50:00',11)
INSERT INTO Route VALUES(12,'6:15:00','7:35:00',12)
INSERT INTO Route VALUES(13,'6:15:00','7:40:00',13)

INSERT INTO Bus_Stops VALUES('Petrol Bunk',11,'HSR Layout',1)
INSERT INTO Bus_Stops VALUES('Belgian Waffle',12,'HSR Layout',1)
INSERT INTO Bus_Stops VALUES('CPWD',13,'HSR Layout',1)
INSERT INTO Bus_Stops VALUES('BDA Park',14,'HSR Layout',1)
INSERT INTO Bus_Stops VALUES('Mangammanpalya',15,'HSR Layout',1)
INSERT INTO Bus_Stops VALUES('Kudlu Gate',16,'HSR Layout',1)
INSERT INTO Bus_Stops VALUES('Central Jail',17,'HSR Layout',1)

INSERT INTO Bus_Stops VALUES('Shalini Ground',21,'Jayanagar',2)
INSERT INTO Bus_Stops VALUES('Depot',22,'Jayanagar',2)
INSERT INTO Bus_Stops VALUES('SVM School',23,'Jayanagar',2)
INSERT INTO Bus_Stops VALUES('St Peters',24,'Jayanagar',2)
INSERT INTO Bus_Stops VALUES('Thilaknagar',25,'Jayanagar',2)
INSERT INTO Bus_Stops VALUES('Vasan Eye Care',26,'Jayanagar',2)

INSERT INTO Bus_Stops VALUES('Central Mall',31,'JP Nagar',3)
INSERT INTO Bus_Stops VALUES('Manipal Hospital',32,'JP Nagar',3)
INSERT INTO Bus_Stops VALUES('Woodys',33,'JP Nagar',3)
INSERT INTO Bus_Stops VALUES('Ragi Gudda',34,'JP Nagar',3)
INSERT INTO Bus_Stops VALUES('Jain College',35,'JP Nagar',3)
INSERT INTO Bus_Stops VALUES('Flyover',36,'JP Nagar',3)
INSERT INTO Bus_Stops VALUES('Junction',37,'JP Nagar',3)

INSERT INTO Bus_Stops VALUES('BTM Phase 1',41,'BTM Layout',4)
INSERT INTO Bus_Stops VALUES('BTM Phase 2',42,'BTM Layout',4)
INSERT INTO Bus_Stops VALUES('BTM Phase 3',43,'BTM Layout',4)
INSERT INTO Bus_Stops VALUES('BTM Phase 4',44,'BTM Layout',4)
INSERT INTO Bus_Stops VALUES('BTM Phase 5',45,'BTM Layout',4)
INSERT INTO Bus_Stops VALUES('BTM Phase 6',46,'BTM Layout',4)

INSERT INTO Bus_Stops VALUES('Rullsel Market',51,'Shivajinagar',5)
INSERT INTO Bus_Stops VALUES('Basilica',52,'Shivajinagar',5)
INSERT INTO Bus_Stops VALUES('MG Park',53,'Shivajinagar',5)
INSERT INTO Bus_Stops VALUES('Tipu Palace',54,'Shivajinagar',5)

INSERT INTO Bus_Stops VALUES('Museum',61,'Marathalli',6)
INSERT INTO Bus_Stops VALUES('Lake Park',62,'Marathalli',6)
INSERT INTO Bus_Stops VALUES('Life on Wall',63,'Marathalli',6)
INSERT INTO Bus_Stops VALUES('Marathalli Mall',64,'Marathalli',6)
INSERT INTO Bus_Stops VALUES('HAL Aerospace',65,'Marathalli',6)

INSERT INTO Bus_Stops VALUES('Onnama Temple',71,'Hebbagodi',7)
INSERT INTO Bus_Stops VALUES('St Marys School',72,'Hebbagodi',7)
INSERT INTO Bus_Stops VALUES('Sai Baba temple',73,'Hebbagodi',7)
INSERT INTO Bus_Stops VALUES('Police Station',74,'Hebbagodi',7)
INSERT INTO Bus_Stops VALUES('Sridevi Complex',75,'Hebbagodi',7)
INSERT INTO Bus_Stops VALUES('Rama Temple',76,'Hebbagodi',7)

INSERT INTO Bus_Stops VALUES('Subway',81,'Ecity',8)
INSERT INTO Bus_Stops VALUES('Infosys',82,'Ecity',8)
INSERT INTO Bus_Stops VALUES('Wipro',83,'Ecity',8)
INSERT INTO Bus_Stops VALUES('TCS',84,'Ecity',8)
INSERT INTO Bus_Stops VALUES('PES College',85,'Ecity',8)

INSERT INTO Bus_Stops VALUES('Dommasandra',91,'Sarjapur',9)
INSERT INTO Bus_Stops VALUES('Belezia',92,'Sarjapur',9)
INSERT INTO Bus_Stops VALUES('Mango Farm',93,'Sarjapur',9)
INSERT INTO Bus_Stops VALUES('Potters Nursery',94,'Sarjapur',9)
INSERT INTO Bus_Stops VALUES('Eleganza',95,'Sarjapur',9)

INSERT INTO Bus_Stops VALUES('Shegekoti',101,'Kanakpura',10)
INSERT INTO Bus_Stops VALUES('Tigalrapura',102,'Kanakpura',10)
INSERT INTO Bus_Stops VALUES('Temple Farms',103,'Kanakpura',10)
INSERT INTO Bus_Stops VALUES('Pyramid Valley',104,'Kanakpura',10)
INSERT INTO Bus_Stops VALUES('Art of Living',105,'Kanakpura',10)

INSERT INTO Bus_Stops VALUES('BMTC Depot',111,'Wilson Garden',11)
INSERT INTO Bus_Stops VALUES('BDA Ground',112,'Wilson Garden',11)
INSERT INTO Bus_Stops VALUES('Lakkasandra Extension',113,'Wilson Garden',11)
INSERT INTO Bus_Stops VALUES('Homegowda School',114,'Wilson Garden',11)
INSERT INTO Bus_Stops VALUES('Nimhans Hall',115,'Wilson Garden',11)

INSERT INTO Bus_Stops VALUES('Mary Immaculate School',121,'Lakkasandra',12)
INSERT INTO Bus_Stops VALUES('Surya Jewels',122,'Lakkasandra',12)
INSERT INTO Bus_Stops VALUES('Balaji Electricals',123,'Lakkasandra',12)
INSERT INTO Bus_Stops VALUES('Shettys Stores',124,'Lakkasandra',12)
INSERT INTO Bus_Stops VALUES('Janata Hotel',125,'Lakkasandra',12)

INSERT INTO Bus_Stops VALUES('PNR School',131,'Koramangala',13)
INSERT INTO Bus_Stops VALUES('Base Tutorials',132,'Koramangala',13)
INSERT INTO Bus_Stops VALUES('Allen Tutorials',133,'Koramangala',13)
INSERT INTO Bus_Stops VALUES('Forum Mall',134,'Koramangala',13)
INSERT INTO Bus_Stops VALUES('Bosch Head Office',135,'Koramangala',13)

select * from Bus_Stops